services:
  postgres:
    image: postgres:18.3-bookworm
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5437:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

volumes:
  pgdata:
