name = "mlack"
main = "hono/index.ts"
compatibility_date = "2025-03-26"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./public"
not_found_handling = "none"

[[d1_databases]]
binding = "DB"
database_name = "mlack-db"
database_id = "local"
migrations_dir = "hono/db/migrations"

[[durable_objects.bindings]]
name = "CHAT_ROOM"
class_name = "ChatRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ChatRoom"]

[vars]
NODE_ENV = "production"
