name = "mlack"
main = "hono/index.ts"
compatibility_date = "2025-03-26"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./public"
not_found_handling = "none"

[[d1_databases]]
binding = "DB"
database_name = "mlack-db"
database_id = "local"
migrations_dir = "hono/db/migrations"

[[durable_objects.bindings]]
name = "CHAT_ROOM"
class_name = "ChatRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ChatRoom"]

[vars]
NODE_ENV = "development"

[env.production]
routes = [
  { pattern = "mlack.uk", custom_domain = true }
]

[env.production.vars]
NODE_ENV = "production"

[[env.production.d1_databases]]
binding = "DB"
database_name = "mlack-db"
database_id = "d6405044-202a-4a50-9612-089512467c9e"
migrations_dir = "hono/db/migrations"

[[env.production.durable_objects.bindings]]
name = "CHAT_ROOM"
class_name = "ChatRoom"

[[env.production.migrations]]
tag = "v1"
new_sqlite_classes = ["ChatRoom"]
